### ISSUE TITLE
Items inside each Box are not staying underneath their box

### ISSUE THREAD

**Issue by charlie-quinn** [charlie-quinn/dsn1676-term-project#1]
![screen shot 2015-03-22 at 1 17 33 pm](https://cloud.githubusercontent.com/assets/6362454/6770428/dd3cf2f6-d095-11e4-8cdc-641b193a5489.png)
![screen shot 2015-03-22 at 1 17 47 pm](https://cloud.githubusercontent.com/assets/6362454/6770430/e097bbe8-d095-11e4-9c77-87212dd80ea6.png)
In the second screen caption, the items are supposed to be under the Science Stuff box.

Help! :( @thomasjbradley

**Comment by thomasjbradley** [comment]
This is a problem with the organization of HTML, we’d need to have the science stuff come immediately after the science box. But, I see you're using the tabs example, I think because of the way that HTML is organized you can't complete the layout you want. You'll have to change the HTML order: make it work on small screens first.
